import './globals.css'
import Header from './components/Header'
import Sections from './components/Sections'


export const metadata = {
  title: 'Song Tube',
  description: 'Generated by create next app',
}

// Import Inter font
import { Noto_Sans } from 'next/font/google'

const noto_sans = Noto_Sans({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={noto_sans.className}>
      <body>
        <Header />
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
